<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
    <dict>
        <key>fileTypes</key>
        <array>
            <string>hdl</string>
        </array>
        <key>name</key>
        <string>HDL</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>\b(CHIP|BUILTIN|IN|OUT|PARTS|CLOCKED)\b</string>
                <key>name</key>
                <string>keyword.language.hdl</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(Add16|ALU|And|And16|ARegister|Bit|CPU|DFF|DMux|DMux4Way|DMux8Way|DRegister|FullAdder|HalfAdder|Inc16|Keyboard|Memory|Mux|Mux4Way16|Mux8Way16|Mux16|Nand|Not|Not16|Or|Or8Way|Or16|PC|RAM4K|RAM8|RAM16K|RAM64|RAM512|Register|ROM32K|Screen|Xor)\b</string>
                <key>name</key>
                <string>support.function.hdl</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>/\*</string>
                <key>end</key>
                <string>\*/</string>
                <key>name</key>
                <string>comment.block.hdl</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>//</string>
                <key>end</key>
                <string>$\n?</string>
                <key>name</key>
                <string>comment.line.double-slash.hdl</string>
            </dict>
        </array>
        <key>scopeName</key>
        <string>source.hdl</string>
    </dict>
</plist>
