<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
    <dict>
        <key>fileTypes</key>
        <array>
            <string>hdl</string>
        </array>
        <key>name</key>
        <string>HDL</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>\bCHIP\b</string>
                <key>name</key>
                <string>storage.type.hdl</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(BUILTIN|PARTS|CLOCKED)\b</string>
                <key>name</key>
                <string>keyword.language.hdl</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(IN|OUT)\b</string>
                <key>name</key>
                <string>variable.parameter.hdl</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b\w+(?=\()\b</string>
                <key>name</key>
                <string>support.function.hdl</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>/\*</string>
                <key>end</key>
                <string>\*/</string>
                <key>name</key>
                <string>comment.block.hdl</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>//</string>
                <key>end</key>
                <string>$\n?</string>
                <key>name</key>
                <string>comment.line.double-slash.hdl</string>
            </dict>
        </array>
        <key>scopeName</key>
        <string>source.hdl</string>
    </dict>
</plist>
